### ISSUE TITLE
Peer to peer code review - Week 4, day 2

### ISSUE THREAD

**Issue by danigalindo10** [wadaudzai/Portfolio-setup-and-mobile-version-skeleton#10]
### Recommendations 👍 
- One recommendation I could make to your project, it's to try to change your indentation spaces from 4 to 2, I think that it's visually more attractive and order. 😃 
- Another recommendation our group can share with you is to put some comments between the sections you are writing. 😃

**Comment by wadaudzai** [comment]
Hello Dear Daniel,
Thank you so much for your kind comment. I tried to change the indentation but I got into issues with the linters. Then I decided to leave it as it is. Your recommendation about comments was awesome I will try my best to use comments in every part of my code after this.
